SET SCHEMA PUBLIC;

create table if not exists users
(
    id    int8 generated by default as identity,
    username varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null,
    primary key (id)
);

insert into users (username, password, role) values ('admin', 'admin', 'ADMIN');
insert into users (username, password, role) values ('user', 'user', 'USER');

